language: go
go:
  - 1.13.x
env:
  - GO111MODULE=on
before_install:
  - go get -t -v ./...
  - go install github.com/golangci/golangci-lint/cmd/golangci-lint
script:
  - golangci-lint run --enable-all -D wsl -D gochecknoglobals -D gochecknoinits -D lll
  - go test -v -race ./...
